### ISSUE TITLE
分页页码无法在页面显示

### ISSUE THREAD

**Issue by Altamill** [keenwon/jqPaginator#10]
hello，用了jqpaginator之后，发现2个问题。
1.分页页码无法显示在html里。server能获取到点击的页码（num）
2.根据前端后续返回的页码无法使sql中的数据return回前端页面。（页面一直显示首次查询的数据）

**Comment by keenwon** [comment]
1. 贴代码上来
2. 这个和 jqPaginator 没关系吧

**Comment by Altamill** [comment]
好的代码如下，我也是刚接触的菜鸟，虚心求教。谢谢
app = Flask(__name__, static_folder='', static_url_path='')
@app.route('/borrowlist',methods=['GET'])
def index():
    try:
        pagenum = int(request.args.get('num'))
    except (TypeError, ValueError):
        pagenum = 1

    # 通过 sql 的 count 查询确认总数,最终得到总页数
    conn=MySQLdb.connect(host="localhost",user="root",passwd="123456",db="borrow",charset="utf8")
    cur = conn.cursor()
    sql = "select count(*) from borrow_list"
    cur.execute(sql)
    for row in cur.fetchall():
        totalCounts = row[0]
    # 取分页内的数据

    pageSize = 15
    n = str((pagenum-1)*pageSize)
    m = str(pageSize)

    conn=MySQLdb.connect(host="localhost",user="root",passwd="123456",db="borrow",charset="utf8")
    cur = conn.cursor()
    sql = "select * from borrow_list order by id desc limit "+n+","+m
    cur.execute(sql)
    entries = [dict(id=row[0], name=row[1], assetid=row[2], dname=row[3], borrow_date=row[4], return_date=row[5], dtype=row[6], state=row[7]) for row in cur.fetchall()]

    return render_template('borrowlistyp.html', entries=entries, totalCounts=totalCounts, pageSize=pageSize)

if __name__ == '__main__':
    app.run(debug = True , host='0.0.0.0')

**Comment by Altamill** [comment]
<div class="demo" style="text-align:center">
            <p id="demo1-text"></p>
            <ul id="demo1" class="pagination"></ul>
        </div>

<script type="text/javascript">
$(function(){
   $("#demo1").jqPaginator({
       totalCounts:{{totalCounts}},
       pageSize:{{pageSize}},
       visiblePages: 9,
       currentPage: 1,
       first: '<li class="first"><a href="javascript:void(0);">First<\/a><\/li>',
       prev: '<li class="prev"><a href="javascript:void(0);">Previous<\/a><\/li>',
       next: '<li class="next"><a href="javascript:void(0);">Next<\/a><\/li>',
       last: '<li class="last"><a href="javascript:void(0);">Last<\/a><\/li>',
       page: '<li class="page"><a href="javascript:void(0);">{{page}}<\/a><\/li>',
       onPageChange: function (n, type) {
           $("#demo1-text").html("当前第" + n + "页");
       $.ajax({
         url:"/borrowlist",
         type:"GET",
         data:{'num': n},
         datetype:"text",
         success: function(data) {
//             if (data == 'ok') {
//                 window.location.reload();
//             }
         }
       });
       }
    });
})
</script>

**Comment by Altamill** [comment]
`        <div class="demo" style="text-align:center">
            <p id="demo1-text"></p>
            <ul id="demo1" class="pagination"></ul>
        </div>

<script type="text/javascript">
$(function(){
   $("#demo1").jqPaginator({
       totalCounts:{{totalCounts}},
       pageSize:{{pageSize}},
       visiblePages: 9,
       currentPage: 1,
       first: '<li class="first"><a href="javascript:void(0);">First<\/a><\/li>',
       prev: '<li class="prev"><a href="javascript:void(0);">Previous<\/a><\/li>',
       next: '<li class="next"><a href="javascript:void(0);">Next<\/a><\/li>',
       last: '<li class="last"><a href="javascript:void(0);">Last<\/a><\/li>',
       page: '<li class="page"><a href="javascript:void(0);">{{page}}<\/a><\/li>',
       onPageChange: function (n, type) {
           $("#demo1-text").html("当前第" + n + "页");
       $.ajax({
         url:"/borrowlist",
         type:"GET",
         data:{'num': n},
         datetype:"text",
         success: function(data) {
//             if (data == 'ok') {
//                 window.location.reload();
//             }
         }
       });
       }
    });
})
</script>

`

**Comment by keenwon** [comment]
这是啥代码？我只关注js相关的
数据库查询的和前端组件显然没啥关系

**Comment by Altamill** [comment]
`        <div class="demo" style="text-align:center">
            <p id="demo1-text"></p>
            <ul id="demo1" class="pagination"></ul>
        </div>

<script type="text/javascript">
$(function(){
   $("#demo1").jqPaginator({
       totalCounts:{{totalCounts}},
       pageSize:{{pageSize}},
       visiblePages: 9,
       currentPage: 1,
       first: '<li class="first"><a href="javascript:void(0);">First<\/a><\/li>',
       prev: '<li class="prev"><a href="javascript:void(0);">Previous<\/a><\/li>',
       next: '<li class="next"><a href="javascript:void(0);">Next<\/a><\/li>',
       last: '<li class="last"><a href="javascript:void(0);">Last<\/a><\/li>',
       page: '<li class="page"><a href="javascript:void(0);">{{page}}<\/a><\/li>',
       onPageChange: function (n, type) {
           $("#demo1-text").html("当前第" + n + "页");
       $.ajax({
         url:"/borrowlist",
         type:"GET",
         data:{'num': n},
         datetype:"text",
         success: function(data) {
//             if (data == 'ok') {
//                 window.location.reload();
//             }
         }
       });
       }
    });
})
</script>
`

**Comment by keenwon** [comment]
我觉得你应该先了解下 markdown 怎么写

```js
$(function(){ 
  $("#demo1").jqPaginator({ 
    totalCounts:{{totalCounts}}, 
    pageSize:{{pageSize}}, 
    visiblePages: 9, 
    currentPage: 1, 
    first: 'First<\/a><\/li>', 
    prev: 'Previous<\/a><\/li>', 
    next: 'Next<\/a><\/li>', 
    last: 'Last<\/a><\/li>', 
    page: '{{page}}<\/a><\/li>', 
    onPageChange: function (n, type) { 
      $("#demo1-text").html("当前第" + n + "页"); 
      $.ajax({ 
        url:"/borrowlist", 
        type:"GET", 
        data:{'num': n}, 
        datetype: "text", 
        success: function(data) { 
          // if (data == 'ok') { 
          // window.location.reload(); 
          // } 
        } 
      }); 
    }
  });
})
```

你用的大体上没问题，但是......

- 你的 `first` 等为什么只有闭标签？
- `success` 之后为什么要 `reload`？

**Comment by Altamill** [comment]
感谢！
first这些我感觉是因为github我直接贴代码造成的。其实是直接从你页面上复制的源码。
success我把它注释了

**Comment by Altamill** [comment]
![640a4c06-f860-46fe-a5cc-b330fb73d5b7](https://cloud.githubusercontent.com/assets/22368026/25371418/4c065a82-29c3-11e7-9062-264745826a3b.png)

**Comment by keenwon** [comment]
看上去并没有什么错，只要你能保证 `{{totalCounts}}` 和 `{{pageSize}}` 输出正确，如果“当前第n页”输出没错的话，jqPaginator就是正常的

**Comment by Altamill** [comment]
确实我也不是很清楚是为什么。你可以看到如下图片：
并没有页码，这个页码应该是自动填充的？
我点击第二个li之后输出的当前页确实是正确的。但是页面上的数据并没有更新。
![e87690e3-9916-453f-870f-35a0a54ef0b4](https://cloud.githubusercontent.com/assets/22368026/25371664/697f3c4a-29c4-11e7-9ba7-da9aa30bb6b7.png)

**Comment by keenwon** [comment]
```
totalCounts:{{totalCounts}}
pageSize:{{pageSize}}
```

这两行中的 `{{ }}`应该是你的后端模板，我猜测，刚好和 jqPaginator 的 `page` 里的 `{{page}}` 冲突了

**Comment by Altamill** [comment]
然而我重命名参数之后还是和之前一样。

**Comment by keenwon** [comment]
不是参数的问题，是模板语法的问题

在生成 html 后，page参数里面已经没有 `{{page}}`，当然也就显示不了分页了。这只是我的猜测，你可以查看源代码验证下。

**Comment by Altamill** [comment]
是这样，这2个参数totalcounts是我从数据库统计出来转成string的。
pagesize是我指定的也转成了string。
因为对于后面sql拼接中他提示must be str not int。所以这2个参数应该不存在模板这一说吧

我还想确认一点就是，page这个参数是根据上面2个参数自动生成页码的还是一定要我从后端模板return进{{page}}

**Comment by keenwon** [comment]
自动生成

**Comment by Altamill** [comment]
稍等我给你在看一个截图，图中2个参数应该都是正常的。是否会因为是str的原因造成无法计算page

![117100d9-d628-4431-856b-d085f07bdcf8](https://cloud.githubusercontent.com/assets/22368026/25372632/bc761b40-29c8-11e7-824e-dd4dab4d1c82.png)

**Comment by keenwon** [comment]
https://github.com/keenwon/jqPaginator/blob/master/src/js/jqPaginator.js#L41

**Comment by Altamill** [comment]
我看到了你标出的，但我不是很理解，麻烦还是说下，谢谢

**Comment by keenwon** [comment]
你上面的截图是源代码吧？截大一点

**Comment by Altamill** [comment]
这样可以么
![d5ea49ed-ad7e-498e-abe1-bcb2601b1021](https://cloud.githubusercontent.com/assets/22368026/25373485/6beee3ec-29cc-11e7-9c92-d9bd0d572cef.png)

**Comment by keenwon** [comment]
![image](https://cloud.githubusercontent.com/assets/5516478/25373521/9a5672cc-29cc-11e7-88ff-4461e7d50637.png)

>不是参数的问题，是模板语法的问题
>
>在生成 html 后，page参数里面已经没有 {{page}}，当然也就显示不了分页了。这只是我的猜测，你可以>查看源代码验证下。

这样明白了吗？你后端模板语法和 jqpaginator 冲突了，生成的html `{{page}}` 没了，当然没法显示页码了。

**Comment by Altamill** [comment]
哦这个意思。。那也就是说我只能调整后端了是么

**Comment by keenwon** [comment]
至于这么解决，需要具体情况具体分析，目前 jqPaginator 不支持自定义模板语法。

这不是 jqPaginator 的bug，此 issue 先关闭了，jqPaginator 有问题再新启 issue。

**Comment by Altamill** [comment]
好的，感谢！

**Comment by Cai-Wencong** [comment]
遇到一样的问题，模版语法和jqPaginator语言一样造成的冲突，试了半天找到解决方案了，模版语法那边也设置page参数，值就是'{{page}}'，亲测有效
