### ISSUE TITLE
分页无页码关于自己模板的一些问题

### ISSUE THREAD

**Issue by Altamill** [keenwon/jqPaginator#11]
hello，前面看了下你说的现在jqPaginator不支持自定义模板。我还有些不解。
如果不支持自定义模板我就没法吧总页数和每页的条目数返回给前端。
我一旦使用return就会造成与jqPaginator冲突，这感觉是个死循环。
是否有什么解决方法的建议？
注：虽然页面没有看到页码，但是`<p id="demo1-text"></p>`中可以看到页码，可以确定只是无法显示？

**Comment by keenwon** [comment]
问题你也清楚了，具体解决方案还是需要你根据项目情况制定。
我两眼一抹黑，能够定位问题已是极限了，没法给出**合理**的建议。

**Comment by Altamill** [comment]
好的，虽然有点小遗憾，还是非常感谢~
