### ISSUE TITLE
页面刷新问题

### ISSUE THREAD

**Issue by Altamill** [keenwon/jqPaginator#12]
hello~还有个问题我在onPageChange下面写了`window.location.href = window.location.pathname + "?num=" + n;`，希望他返回一个url？num=n。
原因是我测试时直接输入url？num=1或者其他数字的时候，页面是有反馈给我要得东西。但是我加了上面那句之后页面就一直刷新，是因为onPageChange一直初始化后触发change事件么？
![33dff4e1-cdf8-4020-a59c-bfa81cd9de69](https://cloud.githubusercontent.com/assets/22368026/25424638/97884636-2a9b-11e7-8cfc-08b593c8901a.png)

**Comment by keenwon** [comment]
看文档里关于 `onPageChange` 的解释 http://jqpaginator.keenwon.com/

**Comment by Altamill** [comment]
我有什么办法阻止这个change么？

**Comment by keenwon** [comment]
判断传入的参数，不符合你的条件 `return` 不就好了？
**建议你先看看书或者教程什么的**

**Comment by WHJmaxne** [comment]
你好，请问一下，我在一个html也里面有两组分页，页码条的问题怎么解决？
![n l9 v ht2ma r 3cx](https://cloud.githubusercontent.com/assets/24425190/26060116/a606d2de-39b6-11e7-9066-d83b85255ebc.png)

**Comment by keenwon** [comment]
两个也不影响啊，你看下Demo页，有N多个

**Comment by WHJmaxne** [comment]
Demo在源码里吗

**Comment by keenwon** [comment]
右键查看源代码。js代码都在html里。

**Comment by WHJmaxne** [comment]
o.o我傻了  还有个问题想请教一下

**Comment by WHJmaxne** [comment]
就是totalpages是先赋值，我就得先走一遍数据库查出多少条数据赋值给他，再在onPageChange中去请求数据，这样理解对吗？

**Comment by WHJmaxne** [comment]
但是这样的话我每次查询的都要请求至少两次数据库，还请大神指点一下，怎么解决这个问题，我是小白啊0.0

**Comment by Altamill** [comment]
我用的是flask的return render_template方法，把从数据库中统计好的totalpages返回到他的{{totalpages}}中

**Comment by WHJmaxne** [comment]
这个确实没接触过，有什么demo可以参考一下吗？

**Comment by keenwon** [comment]
@WHJmaxne 

你可以一个请求取到 totalPage 和 list, onPageChange 方法用来触发其他页，依然是取到 totalPage 和 list.

**Comment by WHJmaxne** [comment]
写一个方法在之前请求一次，再在onPageChange的时候再请求一次？

**Comment by WHJmaxne** [comment]
就是你那里有那个flask的return render_template的demo吗？能不能麻烦给我发一下？

**Comment by keenwon** [comment]
@WHJmaxne 

此 issue 先关闭，你的问题和当前主题没关系。

如果你的问题和这个 issue 没关系，建议新开个 issue 单独讨论，直接回复会影响到其他人（除非同一个问题）

参考：

```js
function ajax (pageIndex) {
  $.ajax({
    url: "url",
    data: {
      pageIndex: pageIndex
    },
    success: function () {
      initPgae(totalPage, list);
    }
  })
}

function initPage (totalPage, list) {
  // render

  $('#id').jqPaginator({
    totalPages: totalPage,
    visiblePages: 10,
    currentPage: 1,
    onPageChange: function (num, type) {
      if (type !== 'init') {
        ajax(num);
      }
    }
  });
}
```

**Comment by WHJmaxne** [comment]
好的！谢谢了

**Comment by Altamill** [comment]
新开个吧，我里面回复你下
