### ISSUE TITLE
关于totalPages赋值问题

### ISSUE THREAD

**Issue by WHJmaxne** [keenwon/jqPaginator#14]
#### 环境信息

- 系统:
- 浏览器及其版本:

#### 代码片段:

```js

```
  
#### 复现步骤:

1.
2.

**Comment by keenwon** [comment]
你真懒啊，只写了个标题，内容都是空的。

参考: https://github.com/keenwon/jqPaginator/issues/12#issuecomment-301489120

Altamill 的方案可以参考，但是他的方案可能和你说的并不一样，我理解你应该是全 ajax

**Comment by Altamill** [comment]
系统：linux centos 7.2
IDE：python3.6
浏览器随意了

前端jq：`<script type="text/javascript">
$(function(){
   $("#demo1").jqPaginator({
       totalCounts:{{totalCounts}},
       pageSize:{{pageSize}},
       visiblePages: 9,
       currentPage: {{pageNum}},
       first: '<li class="first"><a href="javascript:void(0);">First<\/a><\/li>',
       prev: '<li class="prev"><a href="javascript:void(0);">Previous<\/a><\/li>',
       next: '<li class="next"><a href="javascript:void(0);">Next<\/a><\/li>',
       last: '<li class="last"><a href="javascript:void(0);">Last<\/a><\/li>',
       page: '<li class="page"><a href="javascript:void(0);">{% raw %}{{page}}{% endraw %}<\/a><\/li>',
       onPageChange: function (n, type) {
           if(type == "init"){
               return;
               }else{
                    window.location.href = window.location.pathname + "?num=" + n;}
       }
    });
})
</script>
`

后端：采用flask， render_template方法。
`<script type="text/javascript">
$(function(){
   $("#demo1").jqPaginator({
       totalCounts:{{totalCounts}},
       pageSize:{{pageSize}},
       visiblePages: 9,
       currentPage: {{pageNum}},
       first: '<li class="first"><a href="javascript:void(0);">First<\/a><\/li>',
       prev: '<li class="prev"><a href="javascript:void(0);">Previous<\/a><\/li>',
       next: '<li class="next"><a href="javascript:void(0);">Next<\/a><\/li>',
       last: '<li class="last"><a href="javascript:void(0);">Last<\/a><\/li>',
       page: '<li class="page"><a href="javascript:void(0);">{% raw %}{{page}}{% endraw %}<\/a><\/li>',
       onPageChange: function (n, type) {
           if(type == "init"){
               return;
               }else{
                    window.location.href = window.location.pathname + "?num=" + n;}
       }
    });
})
</script>
`
如果其他人有更好的方法，也请麻烦回复~

**Comment by WHJmaxne** [comment]
我是写.net的，没接触过这个，烧瓶+render_template，刚才百度了一下，全是python的。0.0

**Comment by Altamill** [comment]
哦。。那就比较麻烦了，不对口

**Comment by WHJmaxne** [comment]
0.0 很惆怅

**Comment by Altamill** [comment]
系统：centos7.2
python3.6
flask

前端：` <div class="demo" style="text-align:right">
            <ul id="demo1" class="pagination"></ul>
        </div>
`
前端jq：`<script type="text/javascript">
$(function(){
   $("#demo1").jqPaginator({
       totalCounts:{{totalCounts}},
       pageSize:{{pageSize}},
       visiblePages: 9,
       currentPage: {{pageNum}},
       first: \'<li class="first"><a href="javascript:void(0);">First<\/a><\/li>',
       prev: \'<li class="prev"><a href="javascript:void(0);">Previous<\/a><\/li>',
       next: \'<li class="next"><a href="javascript:void(0);">Next<\/a><\/li>',
       last: \'<li class="last"><a href="javascript:void(0);">Last<\/a><\/li>',
       page:\ '<li class="page"><a href="javascript:void(0);">{% raw %}{{page}}{% endraw %}<\/a><\/li>',
       onPageChange: function (n, type) {
           if(type == "init"){
               return;
               }else{
                    window.location.href = window.location.pathname + "?num=" + n;}
       }
    });
})
</script>
`

后端：`@app.route('/borrowlist', methods=['GET'])
def get_list():
# 获取错误当num值或类型error时,pagenum为1
    try:
        pagenum = int(request.args.get('num'))
    except (TypeError, ValueError):
        pagenum = 1

# 通过 sql 的 count 查询确认总数,最终得到总页数
    conn=MySQLdb.connect(host="localhost",user="root",passwd="123456",db="borrow",charset="utf8")
    cur = conn.cursor()
    sql = "select count(*) from borrow_list"
    cur.execute(sql)
    for row in cur.fetchall():
        totalCounts = row[0]
# 取分页内的数据

    pageSize = 15
    n = str((pagenum-1)*pageSize)
    m = str(pageSize)
# 设置 pageSize(每页显示条目数), n(步长),拼接sql

    conn=MySQLdb.connect(host="localhost",user="root",passwd="123456",db="borrow",charset="utf8")
    cur = conn.cursor()
    sql = "select * from borrow_list order by id desc limit "+n+","+m
    cur.execute(sql)
    entries = [dict(id=row[0], name=row[1], assetid=row[2], dname=row[3], borrow_date=row[4], return_date=row[5], dtype=row[6], state=row[7]) for row in cur.fetchall()]
# 将数据赋值到数据集字段供html中{{ 字段 }}使用
    conn.close()

    return render_template('borrowlist.html', entries=entries, totalCounts=totalCounts, pageSize=pageSize, pageNum=pagenum)

`

**Comment by WHJmaxne** [comment]
好的，我看看去，谢谢两位大神了

**Comment by WHJmaxne** [comment]
你好，就是我按照你给的方案写了一下，点击下一页的时候数据显示下一页的，但是页码选中状态还是在第一页，能麻烦帮我看一下吗？
`function ajax(pageIndex) {
            var search = $('#ApplyId').val();
            $.post("/Tender/Tapplys/GetBillList", { "pageIndex": pageIndex, "pageSize": 5, "seachValue": search }, function (data) {
                var jsonData = JSON.parse(data);
                initPage(jsonData.totalCount, jsonData.row, 5);
            });
        }

        function initPage(totalPage, list, pageSize) {
            $('#pagination').jqPaginator({
                pageSize: pageSize,
                totalCounts: totalPage,
                visiblePages: 5,
                currentPage: 1,
                first: '<li class="first"><a href="javascript:void(0);">首页<\/a><\/li>',
                prev: '<li class="prev"><a href="javascript:void(0);">上一页<\/a><\/li>',
                next: '<li class="next"><a href="javascript:void(0);">下一页<\/a><\/li>',
                last: '<li class="last"><a href="javascript:void(0);">末页<\/a><\/li>',
                page: '<li class="page"><a href="javascript:void(0);">{{page}}<\/a><\/li>',
                onPageChange: function (num, type) {
                    if (type !== 'init') {
                        ajax(num);
                    };
                    var billlist = document.getElementById('billlist');
                    var tableBody = billlist.getElementsByTagName('tbody')[0];
                    tableBody.innerHTML = "";
                    var xuhao = (num - 1) * pageSize;
                    for (var i = 0; i < list.length; i++) {
                        xuhao += 1;
                        var tr = tableBody.insertRow(-1);
                        tr.insertCell(-1).innerHTML = '<input type="checkbox" name="billcheck" value="' + list[i].Id + '">';
                        tr.insertCell(-1).innerHTML = xuhao;
                        tr.insertCell(-1).innerHTML = list[i].BillName;
                        tr.insertCell(-1).innerHTML = list[i].BillSpec;
                        tr.insertCell(-1).innerHTML = list[i].BillMata;
                        tr.insertCell(-1).innerHTML = list[i].Unit;
                        tr.insertCell(-1).innerHTML = list[i].BillNum;
                        tr.insertCell(-1).innerHTML = list[i].Price;
                    }
                }
            });
        }`

**Comment by keenwon** [comment]
因为你写死了 1

![image](https://cloud.githubusercontent.com/assets/5516478/26136769/778b0764-3af0-11e7-8423-a8617828483c.png)

**Comment by WHJmaxne** [comment]
找到问题了  谢谢了
