### ISSUE TITLE
例如在列表第五页打开一个页面后希望浏览器回到上一页的时候仍然在第五页有没有什么办法

### ISSUE THREAD

**Issue by qiaoxiaozhuo** [keenwon/jqPaginator#15]
#### 环境信息

- 系统:
- 浏览器及其版本:

#### 代码片段:

```js

```
  
#### 复现步骤:

1.
2.

**Comment by keenwon** [comment]
应该是不支持的（这个需求太奇怪了)

**Comment by keenwon** [comment]
此 Issue 已经很长时间了，不知道你解决了没有，我暂时关闭。如果有什么问题可以继续讨论。
