### ISSUE TITLE
IE7下 样式不对

### ISSUE THREAD

**Issue by igo9go** [keenwon/jqPaginator#16]
#### 环境信息

- 系统: w7
- 浏览器及其版本: IE

#### 代码片段:

```js

```
  
#### 复现步骤: 

1.
2.

**Comment by keenwon** [comment]
jqPaginator 不包含样式
如果你使用了 demo 页里的 bootstrap，可能和你原本的样式有什么冲突
总之，jqPaginator 的最初目的就是实现和 css 的分离
