### ISSUE TITLE
楼主，你这个能自定义一个跳转页的功能吗

### ISSUE THREAD

**Issue by fengjujiao** [keenwon/jqPaginator#160]
#### 环境信息

- 系统:
- 浏览器及其版本:

#### 代码片段:

```js

```
  
#### 复现步骤:

1.
2.

**Comment by keenwon** [comment]
你可以尝试用这个 api 自定义

> $('#id').jqPaginator('option', options)
> 初始化后，动态修改配置
> 
> ```js
> $('#id').jqPaginator('option', {
>     currentPage: 1
> });
> ```

**Comment by fengjujiao** [comment]
好的，谢谢




------------------ 原始邮件 ------------------
发件人: "Keenwon"<notifications@github.com>; 
发送时间: 2019年7月25日(星期四) 上午10:17
收件人: "keenwon/jqPaginator"<jqPaginator@noreply.github.com>; 
抄送: "醉卧沙、君笑"<980592475@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [keenwon/jqPaginator] 楼主，你这个能自定义一个跳转页的功能吗 (#160)




你可以尝试用这个 api 自定义
  
$('#id').jqPaginator('option', options)
 初始化后，动态修改配置
 $('#id').jqPaginator('option', {     currentPage: 1 });
