### ISSUE TITLE
楼主我使用扩展方法，但是给currentPage: index，传入一个index他会报错，但我改为currentPage: 2，给一个固定值，他就不报错，这是怎么回事

### ISSUE THREAD

**Issue by fengjujiao** [keenwon/jqPaginator#161]
#### 环境信息

- 系统:
- 浏览器及其版本:

#### 代码片段:

```js

```
  
#### 
1.Error: [jqPaginator] type error: currentPage
2.

**Comment by keenwon** [comment]
这要你自己调试下了，可能是 index undefined

**Comment by fengjujiao** [comment]
刚刚看了，是值的类型不对，必须要转成number类型的，我已经实现了，谢谢大佬




------------------ 原始邮件 ------------------
发件人: "Keenwon"<notifications@github.com>; 
发送时间: 2019年7月25日(星期四) 中午11:23
收件人: "keenwon/jqPaginator"<jqPaginator@noreply.github.com>; 
抄送: "醉卧沙、君笑"<980592475@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [keenwon/jqPaginator] 楼主我使用扩展方法，但是给currentPage: index，传入一个index他会报错，但我改为currentPage: 2，给一个固定值，他就不报错，这是怎么回事 (#161)




这要你自己调试下了，可能是 index undefined
