### ISSUE TITLE
onPageChange方法加载时会自执行调用下面的方法？

### ISSUE THREAD

**Issue by wufei19920201** [keenwon/jqPaginator#19]
$.jqPaginator('#pagination2', {
                    totalCounts:100,
                    pageSize:2,
                    visiblePages: 5,//可视页码数
                    currentPage: 1,//当前页码
                    onPageChange: function (size, type) {
                        /*orderAjaxRe(10, size);*/
                    }
                });
  
1 一切配置好的前提下，插入上面代码块
2 onPageChange方法里面的函数直接执行了
Q：这个方法不应该是只有页码发生改变的时候才会去执行里面的代码吗？

**Comment by keenwon** [comment]
通过type判断
wufei <notifications@github.com>于2017年7月20日 周四18:11写道：

**Comment by wufei19920201** [comment]
$.jqPaginator('#pagination2', {
                    totalCounts:total,
                    pageSize:2,
                    visiblePages: 5,//可视页码数
                    currentPage: 1,//当前页码
                    onPageChange: function (size, type) {
                        if(type=='change'){
                            orderAjaxRe(2, size);
                            console.log(type);
                        }
                    }
                });
这样判断的话，点击页码。下面页码高亮一直在第一页，改变页面一次过后，首页&上一下&第一页无法点击，回不到第一页。

**Comment by wufei19920201** [comment]
大神可以直接贴出判断代码吗？
