### ISSUE TITLE
从后台请求数据,无论点的是哪一页一定先跳到3页再跳到点击的页面

### ISSUE THREAD

**Issue by Skoala** [keenwon/jqPaginator#21]
#### 环境信息

- 系统:
- 浏览器及其版本:

#### 代码片段:
<input type="hidden" name="pager.pageNo" id="pageNumber" value="${pager.pageNo}" />
<input type="hidden" name="pager.orderBy" id="orderBy" value="${pager.orderBy}" />
<input type="hidden" name="pager.order" id="order" value="${pager.order}" />
<ul class="pagination fr" id="pagination1">
	<li class="first" jp-role="first" jp-data="1">
		<a href="javascript:;">首页</a>
	<>
	<li class="prev" jp-role="prev" jp-data="1">
		<a href="javascript:;">上一页</a>
	</li>
	 
	<li class="next" jp-role="next" jp-data="3">
		<a href="javascript:;">下一页</a>
	</li>
	<li class="last" jp-role="last" jp-data="16">
		<a href="javascript:;">末页</a>
	<>
</ul>
```js
var $total = parseInt($("#p1").find("span").text());
		var $pageSize=parseInt($('#pageSize option:selected').val());
		$pageSize?$pageSize=$pageSize:$pageSize=10;
		var currentPage= parseInt($("#pageNumber").val());
		 
			functionList.jqPaginator('#pagination1', $total,$pageSize,currentPage);
```
  
#### 复现步骤:

1.前后端未分离,总条数是后台传入的,刚进去都会刷1,2,3出来,再跑准确的出来
2.有俩个页面还用了别的插件,他的加载比较慢,但是放在这个分页的后面,按道理是不会影响,再点击比如第7页,会跳3,停2s再调回7,第一个速度很快影响不大,但是第二条很明显
3.怎么改变先跑1,2,3出来,而且3是选中状态,已经看了插件代码跟我写的,没找到3是选中状态这个事情

**Comment by keenwon** [comment]
```js
$('#id').jqPaginator({
    totalPages: 100,
    visiblePages: 10,
    currentPage: 1,
    onPageChange: function (num, type) {
        $('#text').html('当前第' + num + '页');
    }
});
```

`jqPaginator` 接收的是一个对象，`currentPage` 设置当前页，你可以检查下你的代码设置的是不是3

**Comment by Skoala** [comment]
我的是currentPage是去读取一个input type="hidden"的值,他的val值是后台传过来的,默认值是1,感觉很奇怪的是在传给的值进去前都会出现1,2,3,有什么办法可以改变这一行为吗?

**Comment by keenwon** [comment]
完整代码，格式化好，贴上来看看

**Comment by Skoala** [comment]
![image](https://user-images.githubusercontent.com/30100923/28705502-a5f831c2-73a2-11e7-9471-f3c85a8bdbed.png)

**Comment by LionHL** [comment]
@Skoala  1,2,3出现的问题有可能是因为你代码里 jp-data="3"这段代码
![wechatimg40](https://user-images.githubusercontent.com/18711261/28709379-a8ac86ec-73b2-11e7-9d6e-3d4a451e534e.jpeg)


￼
