### ISSUE TITLE
怎么为动态添加的翻页导航添加jqpaginator

### ISSUE THREAD

**Issue by Realiron** [keenwon/jqPaginator#22]
#### 环境信息

- 系统:
- 浏览器及其版本:

#### 代码片段:

```js
$("#pageinfo").append("<ul class='pagination' style='margin-left:30%' id='pagination2'></ul>");
```
  
#### 复现步骤:

1.动态添加的pagination再使用$.jqpaginator无法初始化
2.

**Comment by keenwon** [comment]
添加完直接初始化，有什么问题？

**Comment by Realiron** [comment]
如果是直接在jsp页面上已经写好<ul class='pagination' style='margin-left:30%' id='pagination2'></ul>
然后调用jqpagiantor是可以初始化的，现在是一开始的页面并没有这个ul元素，我是后来动态用jquery
append进去的，再初始化这个动态的ul就无法实现

**Comment by keenwon** [comment]
https://jsbin.com/xotugicici/1/edit?html,css,js,output

**Comment by Realiron** [comment]
$("#pageinfo").empty();
 $("#pageinfo").append("<ul class='pagination' style='margin-left:30%' id='pagination2'></ul>");
 
   
$("#pagination2").jqPaginator({
        	totalPages:3,
        	visiblePages: 5,
        	currentPage: 1,
        	onPageChange: function (num, type) {
        		//var url = "<%=request.getContextPath()%>/course/showcourselist?pagenow="+num+"&pagecount="+${pageinfo.pagecount};
     			if(type=='init'){return;}else{
     			window.location = url;}
     			
            	
        	}
    	});

这样写有什么问题吗

**Comment by Realiron** [comment]
$("#pageinfo").empty();
$("#pageinfo").append("<ul class='pagination' style='margin-left:30%' id='pagination2'></ul>");
 
   		
   		
$("#pagination2").jqPaginator({
        	totalPages:3,
        	visiblePages: 5,
        	currentPage: 1,
        	onPageChange: function (num, type) {
        		//var url = "<%=request.getContextPath()%>/course/showcourselist?pagenow="+num+"&pagecount="+${pageinfo.pagecount};
     			if(type=='init'){return;}else{
     			window.location = url;}
     			
            	
        	}
    	});
  刚才有一个每贴上

**Comment by Realiron** [comment]
$("#pageinfo").append("<ul class='pagination' style='margin-left:30%' id='pagination2'></ul>");
有一句话是这个好像没显示出来

**Comment by keenwon** [comment]
你可以写在 jsbin 里运行

参考: https://jsbin.com/xotugicici/1/edit?html,css,js,output
