### ISSUE TITLE
请问 可以增加页面跳转功能么

### ISSUE THREAD

**Issue by molly-java** [keenwon/jqPaginator#24]
想 新增一个页面跳转框

**Comment by keenwon** [comment]
目前jqPaginaotr没有这个功能，你可以在jqPaginator手动添加

**Comment by YYYCondi** [comment]
为什么只有JS代码啊,生成出来一堆奇形怪状的,这个大概是要自己去调样式吧?

**Comment by keenwon** [comment]
@YYYCondi 是的

**Comment by YYYCondi** [comment]
好迅速啊,这是我第一次看到插件的作者,上周自己写了一个日历的插件,做项目预约,虽然成功了,可是真的简陋的不堪入目.大概确实是太水了,不知道你们这些大牛是怎么做这些插件,感觉自己智商不够啊

**Comment by keenwon** [comment]
@YYYCondi 多写、多看就好了，熟能生巧
