### ISSUE TITLE
请问totalCounts不设置可以吗？怎样从后台获取数据动态分页呢？

### ISSUE THREAD

**Issue by Evocation-hcn** [keenwon/jqPaginator#25]
#### 环境信息

- 系统:
- 浏览器及其版本:

#### 代码片段:

```js

```
  
#### 复现步骤:

1.    $.jqPaginator('#pag-cove', {
        totalCounts: 5,          // 总条数    这个值该怎样动态获取呢
        visiblePages:3,          //最多显示页码
        pageSize: 3,             //每页条数
        currentPage: 1,         //当前页码
        first: '<li class="first"><a href="javascript:;">首页</a></li>',
        prev: '<li class="prev"><a href="javascript:;">上一页</a></li>',
        page: '<li class="page"><a href="javascript:;">{{page}}</a></li>',
        next: '<li class="next"><a href="javascript:;">下一页</a></li>',
        last: '<li class="last"><a href="javascript:;">共{{totalPages}}页</a></li>',
        onPageChange: function(num, type) {
            pagination(num)
        }
    });

2.

**Comment by Evocation-hcn** [comment]
![1504700493 1](https://user-images.githubusercontent.com/20597318/30111672-29137392-9341-11e7-85a4-19893e9b6642.jpg)

**Comment by keenwon** [comment]
1、可以不设置totalCounts，https://jsbin.com/xotugicici/1/edit?html,css,js,output
2、在`onPageChange`中发起异步请求

**Comment by Evocation-hcn** [comment]
好的，非常感谢您
