### ISSUE TITLE
ajax  获取数据并获取数据的总页数，修改totalPages 报错，提示Uncaught TypeError: $.jqPaginator is not a function

### ISSUE THREAD

**Issue by zhizhi1908** [keenwon/jqPaginator#26]
#### 环境信息

- 系统:  ubuntu 
- 浏览器及其版本: chrom  60.0.3112.113

#### 代码片段:

```js
{% block body %}
    <div id="plansItemList" class="plans-item-list"></div>
    <div class="text-center margin-top-20">
        <ul class="pagination jq-pagination" id="pagination"></ul>
    </div>
    <script type="text/javascript">
        $.jqPaginator("#pagination", {
            totalPages: 10,
            visiblePages: 10,
            currentPage: 1,
            onPageChange: function (num, type) {
                if (type === 'change') {
                    search(num);
                }
            }
        });

        function search(num) {
            $.ajax({
                url: '/api/v1/test1',
                type: 'POST',
                dataType: 'json',
                data: JSON.stringify({'limit': 20, 'page': num}),
                success: function (datas) {
                    $("#pagination").jqPaginator('option',{
                        'totalPages': 20
                    })
                }
            })
        }

    </script>

{% endblock %}



```
  
#### 复现步骤:

1.  点击第二页直接报错： Uncaught TypeError: $.jqPaginator is not a function
2.

**Comment by keenwon** [comment]
https://jsbin.com/xotugicici/1/edit?html,css,js,output

最好提供个demo，类似上面的

**Comment by zhizhi1908** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="icon" href="/static/img/favicon.ico"/>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/daterangepicker.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/public.css"/>
    <link rel="stylesheet" type="text/css" href="/static/dist/css/select2.min.css"/>
 
    <script type="text/javascript" src="/static/js/jquery.min.js"></script>
    {#    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>#}
    <script type="text/javascript" src="/static/js/jquery.validate.js"></script>

    <script src="/static/plugins/bootstrap-fileinput/js/plugins/sortable.js" type="text/javascript"></script>
    <script src="/static/plugins/bootstrap-fileinput/js/fileinput.js" type="text/javascript"></script>
    <script src="/static/plugins/bootstrap-fileinput/js/locales/fr.js" type="text/javascript"></script>
    <script src="/static/plugins/bootstrap-fileinput/js/locales/es.js" type="text/javascript"></script>
    <script src="/static/plugins/bootstrap-fileinput/themes/explorer/theme.js" type="text/javascript"></script>

    <script type="text/javascript" src="/static/dist/js/select2.min.js"></script>
    <script type="text/javascript" src="/static/bootstrap-daterangepicker-master/moment.js"></script>
    <script type="text/javascript" src="/static/bootstrap-daterangepicker-master/daterangepicker.js"></script>
    <script type="text/javascript" src="/static/lib/sea.js"></script>
    {#    <script type="text/javascript" src="/static/js/jqPaginator.js"></script>#}
    <script type="text/javascript" src="/static/js/jqPaginator.min.js"></script>
    <script type="text/javascript" src="/static/plugins/bootstrap-typeahead.js"></script>


    
    
    
    
    <script type="text/javascript" src="/static/lib/bootstrap.min.js"></script>
    <script src="/static/lib/datatables/media/js/jquery.dataTables.min.js"></script>
    <script src="/static/lib/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js"></script>


    <script type="text/javascript">
        seajs.config({
            alias: {
                "jquery": "lib/jquery.min.js",
                "bootstrap": "lib/bootstrap.min.js",
                "moment": "lib/moment.js",
                "file-saverjs": "lib/FileSaver"
            },
            base: "/static/"
        });
    </script>
    <style>
        .nav > li > a:focus, .nav > li > a:hover {
            text-decoration: none;
            background-color: transparent;
        }
    </style>
    <title>Solo ERP</title>
</head>
<body class="myrefresh">
<div class="body_show">
    <div id="header">
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/api/v1/index">XXXX</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul v-if="isLogin" class="nav navbar-nav" id="nav_nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">管理<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="/api/v1/overview">概括</a></li>
                                <div class="divider"></div>
                                
                                <li><a href="/api/v1/excel_show/">收入表</a></li>
                                <div class="divider"></div>
                                <li><a href="/api/v1/excel_cost_show/">成本表</a></li>
                                <div class="divider"></div>
                                <li><a href="/api/v1/account_show/">账龄统计</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">客户管理<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">创建客户</a></li>
                                <div class="divider"></div>
                                <li><a href="#">客户列表</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">业务明细<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">PSPM</a></li>
                                <div class="divider"></div>
                                <li><a href="#">PSMS</a></li>
                                <div class="divider"></div>
                                <li><a href="#">PingStart</a></li>
                                <div class="divider"></div>
                                <li><a href="/api/v1/realization">应用变现</a></li>
                                <div class="divider"></div>
                                <li><a href="#">游戏发行</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">公司信息<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="/api/v1/company">添加公司</a></li>
                                <div class="divider"></div>
                                <li><a href="/api/v1/showCompanies">公司列表</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">组织架构<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="/api/v1/orgnization">Organization List</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">审批管理<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="/api/v1/invoiceapply">申请发起</a></li>
                                <div class="divider"></div>
                                <li><a href="/api/v1/archive_the_bill/">归档账单</a></li>
                                <div class="divider"></div>
                                <li><a href="/api/v1/test">测试分页</a></li>

                                {% if session.user== "liyin" or session.user=='hanyuehui' or session.user=='zhangchen' %}
                                    <li><a href="/api/v1/approvalindex">审批管理</a></li>
                                {% endif %}
                            </ul>
                        </li>
                    </ul>
                    <input type="hidden" class="isLogin" value="{{ session.user }}"/>
                    <ul class="nav navbar-right" v-if="isLogin" style="padding: 5px 0">
                        <li class="pub_email"><a href="/api/v1/logout" style="color: #fff;">{{ session.user }}已登录</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div id="contents">
        {% block body %}
        {% endblock %}
    </div>
    <div style="height: 50px;opacity: 0"></div>
    <div id="footer">
        @2016 SoloERP All rights reserved
    </div>
    <div class="mask ">
        <div class="mask_mask box-center">
            <img src="/static/img/loading-2.gif"/>
        </div>
    </div>
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span
                            aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title">Tip</h4>
                </div>
                <div class="modal-body">
                    <p id="content_modal">One fine body&hellip;</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
<script type="text/javascript">
    $(".myfinance").click(function () {
        var fy = {"page": 1, "limit": 20};
        var g_dict = JSON.stringify(fy);
        $.ajax({
            url: "/api/v1/excel_show/",
            type: "POST",
            data: g_dict,
            success: function (datas, status) {
                console.log("_____page,send...", datas);
            }
        })
    });
    seajs.use("js/base", function () {
        $(".body_show").show();
    });
</script>
</html>

**Comment by keenwon** [comment]
解决了？

**Comment by zhizhi1908** [comment]
解决了，html中使用了seajs ，而且默认设置了body 为display:none，导致我每次都无法找到 ，报错了。
改了一下架构就好了，谢谢楼主啦。
