### ISSUE TITLE
没有跳页功能，比如现在总共100页，我要找51的数据，要点太多次，有点麻烦

### ISSUE THREAD

**Issue by qq378488249** [keenwon/jqPaginator#28]
没有跳页功能，比如现在总共100页，我要找51的数据，要点太多次，有点麻烦

**Comment by keenwon** [comment]
是的，没有，如果你需要可以把 jqPaginator 和 ajax 请求一起封装在一个方法里。要调到哪页直接调用

**Comment by keenwon** [comment]
如果还有问题，请新建 Issue 或重新打开此 Issue
