### ISSUE TITLE
总页数为0的时候就报错了，导致其后面的代码都不执行了

### ISSUE THREAD

**Issue by Mywifi** [keenwon/jqPaginator#3]

**Comment by keenwon** [comment]
错误发出来看看

**Comment by Mywifi** [comment]
![image](https://cloud.githubusercontent.com/assets/9286290/12002909/1701a058-ab48-11e5-93db-847aef0cc035.png)
![image](https://cloud.githubusercontent.com/assets/9286290/12002913/318eb3b6-ab48-11e5-9259-a43d07731e8b.png)
你这里的判断是用取反的，那他们等于0的时候也会报错的

**Comment by keenwon** [comment]
总页数是0是个什么概念？只要有一条记录，总页数就是1，否则不要执行jqPaginator方法，直接显示提示之类的就好了

**Comment by Mywifi** [comment]
也行
