### ISSUE TITLE
在onPageChange: 里面不能获取pageSize 吗？

### ISSUE THREAD

**Issue by SUNNINIU** [keenwon/jqPaginator#31]
$.jqPaginator('#pagination1', {
      //  totalPages: 100,
       // visiblePages: 10,
	   totalCounts :200,
	   pageSize:20,
        currentPage: 3,
        onPageChange: function (num, type) {
            $('#p1').text(type + '：' + num);
        }
    });

**Comment by keenwon** [comment]
不能。
`pageSize` 是你设置给 jqPaginator 的，现在你要用，就直接用，还需要 jqPaginator 再给你一次？

**Comment by SUNNINIU** [comment]
已经在用了，谢谢。
