### ISSUE TITLE
一个页面 有两个地方需要用到分页，即使id不同 也会冲突，冲突的结果是有一个会失效

### ISSUE THREAD

**Issue by xiaoxinglai** [keenwon/jqPaginator#33]
#### 环境信息

- 系统:
- 浏览器及其版本:

#### 代码片段:

```js

```
  
#### 复现步骤:

1.在一个页面中，写两次分页
2.都通过ajax去获取数据，然后 其中有一个 分页按钮是无效的

**Comment by xiaoxinglai** [comment]
{"timestamp":1521535506030,"status":404,"error":"Not Found","message":"No message available","path":"/test"}  
同时会出现这个错误？？

**Comment by xiaoxinglai** [comment]
当只有同一页面只有一处分页时不会出现

**Comment by keenwon** [comment]
这个错显然不是 jqPaginator 抛出的。
demo 页面就有同时有很多分页，可以参考。

**Comment by xiaoxinglai** [comment]
$('#id').jqPaginator('option', {
    currentPage: 1
});
这个方法的id选择有问题，我这里两个分页的div是不同的id  但是依然只有其中一个方法有效

**Comment by keenwon** [comment]
http://jsbin.com 
麻烦提供个可运行复现的 demo 参考 https://jsbin.com/wufimex/1/edit?html,css,js,output

**Comment by keenwon** [comment]
如果还问题，reopen
