### ISSUE TITLE
分页使用很完美

### ISSUE THREAD

**Issue by cbxvsli** [keenwon/jqPaginator#34]
十分感谢，分页很完美的实现了
`initPager: function() {
			$(".l-panel-pagebar #jqPager").jqPaginator({
		        //totalPages: 1, 
				totalCounts: 1, 
				pageSize: definePager.pageSize,
		        currentPage: 1, 
		        visiblePages: 6, 
				disableClass: 'disabled',
				activeClass: 'active', 
		        first: '<li class="first"><a href="javascript:void(0);">首页<\/a><\/li>',
		        prev: '<li class="prev"><a href="javascript:void(0);"><i class="arrow arrow2"><\/i>上一页<\/a><\/li>',
		        next: '<li class="next"><a href="javascript:void(0);">下一页<i class="arrow arrow3"><\/i><\/a><\/li>',
		        last: '<li class="last"><a href="javascript:void(0);">末页<\/a><\/li>',
		        page: '<li class="page"><a href="javascript:void(0);">{{page}}<\/a><\/li>'
		    });
		},
		onPageChage: function(eventName) {
			$(".l-panel-pagebar #jqPager").jqPaginator('option', {
		        onPageChange: function (pageIndex) {
					//加载数据
					cpsCommon.doCallback(eval(eventName), [pageIndex]);
		        }
		    });
		},
		dynamicChangePager: function(totalCounts) {
			//给分页组件赋值
			$('.l-panel-pagebar #jqPager').jqPaginator('option', {
		        //currentPage: 1,
				//pageSize: definePager.pageSize,
				totalCounts: totalCounts //设置分页的总条目数
			});
		}`

**Comment by keenwon** [comment]
:clap: :clap: :clap:
