### ISSUE TITLE
如何自定义 传参

### ISSUE THREAD

**Issue by Apple-ljj** [keenwon/jqPaginator#35]
var a,b,c=1
 onPageChange: function (num,type,a,b,c) {
console.log(a,b,c)//无法传入
}
修改 下面代码 可以传 但是 多个页面 用到分页 不传就会报错
   self.fireEvent = function (pageIndex, type) {
            return (typeof self.options.onPageChange !== 'function') || (self.options.onPageChange(pageIndex,type,a,b,c) !== false);
        };

**Comment by keenwon** [comment]
为什么要传入自定义的参数？

**Comment by keenwon** [comment]
如果还有问题，请新建 Issue 或重新打开此 Issue
