### ISSUE TITLE
项目使用的是tornado模板，因此和插件的自定义有冲突（都是使用{{}}来插入动态数据），可否通过其它方式插入？

### ISSUE THREAD

**Issue by cloudeal** [keenwon/jqPaginator#44]
#### 环境信息

- 系统:
- 浏览器及其版本:

#### 代码片段:

```js

```
  
#### 复现步骤:

1.
2.

**Comment by zhuifengshaonianhanlu** [comment]
在python的flask,tornado中因为也是{{}}插入动态数据，因此造成冲突。解决方法：在jq-paginator.js的远吗中讲{{page}}替换成其他的即可，比如&page&。其实主要是把{{}}替换掉，从而避免冲突。

**Comment by keenwon** [comment]
@zhuifengshaonianhanlu thanks!
