### ISSUE TITLE
帅哥 首屏渲染的 默认进入后 onPageChange会直接执行

### ISSUE THREAD

**Issue by SvenZhao** [keenwon/jqPaginator#5]
因为要做首屏渲染 所有默认的时候 不想初始化就执行onpagechange事件?能否加一个flag

**Comment by keenwon** [comment]
`onpagechange`有两个参数，第二是类型，第一次渲染的时候是`init`，判断下不就好了？

**Comment by SvenZhao** [comment]
看到了 不好意思 没注意 看api
