### ISSUE TITLE
Uncaught Error: [jqPaginator] totalCounts or totalPages is required

### ISSUE THREAD

**Issue by JPomichael** [keenwon/jqPaginator#8]
Uncaught Error: [jqPaginator] totalCounts or totalPages is required

        //获取点评
        GetReviews(0);
        _total = GetCounts();

        $('#pagination').jqPaginator({
            totalCounts: _total,
            pageSize: 10,
            visiblePages: 10,
            currentPage: 1,
            first: '<li class="first"><a href="javascript:void(0);">首页<\/a><\/li>',
            prev: '<li class="prev"><a href="javascript:void(0);"><i class="arrow arrow2"><\/i>上一页<\/a><\/li>',
            next: '<li class="next"><a href="javascript:void(0);">下一页<i class="arrow arrow3"><\/i><\/a><\/li>',
            last: '<li class="last"><a href="javascript:void(0);">末页<\/a><\/li>',
            page: '<li class="page"><a href="javascript:void(0);">{{page}}<\/a><\/li>',
            onPageChange: function (num, type) {
                getReviews(num);
            }
        });

**Comment by JPomichael** [comment]
![Uploading image.png…](这你自己写的说明)

**Comment by keenwon** [comment]
断点看下，totalCounts应该是空的

**Comment by JPomichael** [comment]
@keenwon  

    _total = GetCounts(); //这里已经赋值了

**Comment by keenwon** [comment]
https://github.com/keenwon/jqPaginator/blob/master/src/js/jqPaginator.js#L62

你可以看下，你的totalCounts要么是0，要么空
